SELECT ROW_NUMBER() OVER( ORDER BY 1) AS ID,
       SEQ4() AS GENERATED_SEQUENCE,
       UNIFORM(1,200,RANDOM()) AS RANDOMIZED_DATA,
       CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM TABLE(GENERATOR(ROWCOUNT => 200)) v 